---
# Deployment configuration for cPanel - deploys pre-built files from GitHub
deployment:
  tasks:
    - export DEPLOYPATH=/home/grendelm/public_html/grendelmen/
    - /bin/ls -la dist/
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH/
    - /bin/ls -la $DEPLOYPATH
