---
deployment:
  tasks:
    - export DEPLOYPATH=/home/grendelm/public_html/grendelmen/
    - /bin/npm install
    - /bin/npm run build
    - /bin/ls -la dist/
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH/
    - /bin/ls -la $DEPLOYPATH
